### ISSUE TITLE
Add missing WorkspaceChange enum variants

### ISSUE THREAD

**Issue by tmerr** [tmerr/i3ipc-rs#10]
@soumya92 reported he was getting errors on an event workspace:reload

It looks like it has actually been around for a while but it was accidentally left undocumented until recently: https://github.com/i3/i3/pull/2656 . We should add these cases to our WorkspaceChange enum, and probably "move" as well, which is also undocumented but hopefully not for long https://github.com/i3/i3/pull/2847 .

Add the WorkspaceChangeEnum variants `Rename`, `Reload`, `Restored`, `Move`.

**Comment by soumya92** [comment]
Looks like @wawe already fixed this in https://github.com/wawe/i3ipc-rs/commit/94586c2015247afac11aaf115953bcdbd3a86486

**Comment by tmerr** [comment]
I left a comment on his commit to see if he wants wants to create the PR https://github.com/wawe/i3ipc-rs/commit/94586c2015247afac11aaf115953bcdbd3a86486

**Comment by tmerr** [comment]
Went ahead and merged #12
