### ISSUE TITLE
update crates.io to include unreachable code error fix

### ISSUE THREAD

**Issue by bennyandresen** [tmerr/i3ipc-rs#2]
Please update the crates.io package to include the fix for this issue: #1 

Thanks in advance. (Got hit by the same bug just now.)

**Comment by tmerr** [comment]
Good catch, I'll update crates.io tomorrow when I have my laptop with me. In the meantime if you put this in your Cargo.toml it should use the newest version:

`i3ipc = { git = "https://github.com/tmerr/i3ipc-rs.git" }`

**Comment by tmerr** [comment]
Updated.
