### ISSUE TITLE
Implement WindowChange::Mark

### ISSUE THREAD

**Issue by bennyandresen** [tmerr/i3ipc-rs#6]
Sorry if my pull request wasn't as clear, I'm new to debugging Rust.

Marks showing up in the ipc json payload where introduced with i3 version 4.13 and it breaks i3ipc-rs.

Best regards and happy holidays,
Benny

**Comment by tmerr** [comment]
Thank you for this!

The only reason I haven't merged your changes yet is that I want to work out the right way to handle versioning first: see issues #8 and #9.

Cheers,
Trevor

**Comment by tmerr** [comment]
#8 half fixes this by logging a warning instead of hitting an unreachable
